"""initial_schema

Revision ID: 0104d1d44b1a
Revises: 
Create Date: 2026-04-26 15:51:38.901209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0104d1d44b1a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_services_id'), 'services', ['id'], unique=False)
    op.create_index(op.f('ix_services_name'), 'services', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('auth_provider', sa.Enum('GOOGLE', 'LOCAL', name='auth_provider'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('admin', 'client', name='user_role'), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    op.create_table('admin_daily_override',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('admin_id', sa.UUID(), nullable=False),
    sa.Column('date_modified', sa.Date(), nullable=False),
    sa.Column('limit', sa.Integer(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('admin_id', 'date_modified', name='uq_admin_date')
    )
    op.create_index(op.f('ix_admin_daily_override_admin_id'), 'admin_daily_override', ['admin_id'], unique=False)
    op.create_index(op.f('ix_admin_daily_override_date_modified'), 'admin_daily_override', ['date_modified'], unique=False)
    op.create_table('admin_weekly_capacity',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('admin_id', sa.UUID(), nullable=False),
    sa.Column('week_day', sa.Enum('monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday', name='week_day'), nullable=False),
    sa.Column('limit', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('admin_id', 'week_day', name='uq_admin_week_day')
    )
    op.create_index(op.f('ix_admin_weekly_capacity_admin_id'), 'admin_weekly_capacity', ['admin_id'], unique=False)
    op.create_index(op.f('ix_admin_weekly_capacity_id'), 'admin_weekly_capacity', ['id'], unique=False)
    op.create_index(op.f('ix_admin_weekly_capacity_week_day'), 'admin_weekly_capacity', ['week_day'], unique=False)
    op.create_table('appointments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'cancelled', 'completed', name='appointment_status'), server_default='pending', nullable=False),
    sa.Column('cancel_reason', sa.String(length=255), nullable=True),
    sa.Column('refused_reason', sa.String(length=255), nullable=True),
    sa.Column('reschedule_reason', sa.String(length=255), nullable=True),
    sa.Column('payments_method', sa.Enum('dinheiro', 'cartão de débito', 'cartão de crédito', 'pix', name='payments_method'), server_default='dinheiro', nullable=False),
    sa.Column('proposed_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refused_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reschedule_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('admin_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('accepted_by', sa.UUID(), nullable=True),
    sa.Column('refused_by', sa.UUID(), nullable=True),
    sa.Column('cancelled_by', sa.UUID(), nullable=True),
    sa.Column('reschedule_requested_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['accepted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['cancelled_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['refused_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reschedule_requested_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointments_accepted_by'), 'appointments', ['accepted_by'], unique=False)
    op.create_index(op.f('ix_appointments_admin_id'), 'appointments', ['admin_id'], unique=False)
    op.create_index(op.f('ix_appointments_cancelled_by'), 'appointments', ['cancelled_by'], unique=False)
    op.create_index(op.f('ix_appointments_client_id'), 'appointments', ['client_id'], unique=False)
    op.create_index(op.f('ix_appointments_created_by'), 'appointments', ['created_by'], unique=False)
    op.create_index(op.f('ix_appointments_date'), 'appointments', ['date'], unique=False)
    op.create_index(op.f('ix_appointments_id'), 'appointments', ['id'], unique=False)
    op.create_index(op.f('ix_appointments_refused_by'), 'appointments', ['refused_by'], unique=False)
    op.create_index(op.f('ix_appointments_reschedule_requested_by'), 'appointments', ['reschedule_requested_by'], unique=False)
    op.create_table('appointment_services',
    sa.Column('appointment_id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('appointment_id', 'service_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appointment_services')
    op.drop_index(op.f('ix_appointments_reschedule_requested_by'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_refused_by'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_date'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_created_by'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_client_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_cancelled_by'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_admin_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_accepted_by'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_admin_weekly_capacity_week_day'), table_name='admin_weekly_capacity')
    op.drop_index(op.f('ix_admin_weekly_capacity_id'), table_name='admin_weekly_capacity')
    op.drop_index(op.f('ix_admin_weekly_capacity_admin_id'), table_name='admin_weekly_capacity')
    op.drop_table('admin_weekly_capacity')
    op.drop_index(op.f('ix_admin_daily_override_date_modified'), table_name='admin_daily_override')
    op.drop_index(op.f('ix_admin_daily_override_admin_id'), table_name='admin_daily_override')
    op.drop_table('admin_daily_override')
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_services_name'), table_name='services')
    op.drop_index(op.f('ix_services_id'), table_name='services')
    op.drop_table('services')
    # ### end Alembic commands ###

