"""update appointment model for accept status

Revision ID: 2a84693e21bb
Revises: a620f2e69411
Create Date: 2025-12-25 17:34:16.871792

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2a84693e21bb"
down_revision: Union[str, None] = "a620f2e69411"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Criar o tipo ENUM appointment_status se não existir
    op.execute(
        """
        DO $$ BEGIN
            CREATE TYPE appointment_status AS ENUM ('PENDING', 'ACCEPTED', 'COMPLETED', 'CANCELLED');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;
    """
    )

    # Tornar admin_id nullable primeiro (antes de adicionar a coluna status)
    op.alter_column("appointments", "admin_id", existing_type=sa.UUID(), nullable=True)

    # Adicionar coluna status com valor default para registros existentes
    op.add_column(
        "appointments",
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "ACCEPTED",
                "COMPLETED",
                "CANCELLED",
                name="appointment_status",
                create_type=False,
            ),
            nullable=False,
            server_default="PENDING",
        ),
    )

    op.create_index(
        op.f("ix_appointments_status"), "appointments", ["status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_appointments_status"), table_name="appointments")
    op.drop_column("appointments", "status")
    op.alter_column("appointments", "admin_id", existing_type=sa.UUID(), nullable=False)

    # Remover o tipo ENUM appointment_status
    op.execute("DROP TYPE IF EXISTS appointment_status")
    # ### end Alembic commands ###
