"""add_cancel_reason

Revision ID: 7f2c0186c829
Revises: 591bb6b5165b
Create Date: 2025-12-27 17:27:03.710706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f2c0186c829'
down_revision: Union[str, None] = '591bb6b5165b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('cancel_reason', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'cancel_reason')
    # ### end Alembic commands ###

