"""update service model

Revision ID: a620f2e69411
Revises: 97f594193f49
Create Date: 2025-12-25 16:58:23.791752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a620f2e69411'
down_revision: Union[str, None] = '97f594193f49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_services_name'), table_name='services')
    op.create_index(op.f('ix_services_name'), 'services', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_services_name'), table_name='services')
    op.create_index(op.f('ix_services_name'), 'services', ['name'], unique=False)
    # ### end Alembic commands ###

